### ISSUE TITLE
Doesn't work with swig

### ISSUE THREAD

**Issue by geoffatcircle** [christophercliff/metalsmith-fingerprint#12]

**Comment by geoffatcircle** [comment]
Seems to work if I remove the dot after `fingerprint` in the template:

The `fingerprint` object is accessible from the Handlebars template:

```html
<link href="{{ fingerprint[css/index.css] }}" rel="stylesheet" type="text/css" />
```

**Comment by christophercliff** [comment]
The dot syntax is specific to Handlebars. The important thing is the `fingerprint` object being passed to the templater has the shape:

```js
{
  'css/index.css': 'etc.'
}
```
