### ISSUE TITLE
File are generated but no metadata

### ISSUE THREAD

**Issue by 7wonders** [christophercliff/metalsmith-fingerprint#4]
Title says it all really. The files get generated correctly but I do not get any fingerprint metadata to use in hbars template.

**Comment by christophercliff** [comment]
The test is reporting otherwise: https://github.com/christophercliff/metalsmith-fingerprint/blob/master/test/index.js#L11

Please double check your implementation.

**Comment by 7wonders** [comment]
Strange, the tests also pass for me and if I add console.log(metalsmith.metadata()) in my build.js its printing the following:

```
{ title: 'Test',
  description: 'This is a test.',
  date: Wed Feb 18 2015 02:15:50 GMT+0100 (CET),
  fingerprint: { 'static/css/app.css': 'static/css/app-f5d9ccfe6f72ed3bfbac9580662a0bf3.css' } }
```

I can access title, description and date in my template but fingerprint is returning undefined.

**Comment by christophercliff** [comment]
I suspect your implementation is wrong. If you can post a failing test or runnable script that demonstrates the problem, please re-open.
